### ISSUE TITLE
Diagnosing: does "UNKNOWN SCAN RESPONSE: FAIL" mean the code is incorrect?

### ISSUE THREAD

**Issue by DexrnZacAttack** [vanilla-wiiu/vanilla#101]
does "UNKNOWN SCAN RESPONSE: FAIL" mean the code is incorrect?
If so, why does it not mention anything in the UI... I don't have any idea on how this software works yet, @lunakittyyy is trying to get it working atm and they are only getting that message over and over.

Check their comment for anything else that they mention as it could be an unrelated issue.
AFAIK we have the code correct too.

**Comment by lunakittyyy** [comment]
Hi.
I switched Wi-Fi adapters since I last made an issue in this repo - keep that in mind.

It's supposed to be supported per the Wiki: ``0bda:0811 Realtek Semiconductor Corp. Realtek 8812AU/8821AU 802.11ac WLAN Adapter``

After updating to [this run](https://github.com/vanilla-wiiu/vanilla/actions/runs/11831772663), it simply states "SUBPROCESS" instead of "UNKNOWN SCAN RESPONSE: FAIL"

I was sure to install the drivers listed on the Wiki for adapter compatibility.

I am experiencing this on Fedora Linux 41 (Workstation Edition)

**Comment by DexrnZacAttack** [comment]
> No, it doesn't mean the code is wrong.
> 
> The error is self-explanatory; upon requesting the hardware (or more specifically, `wpa_supplicant_drc`) to scan for networks, Vanilla received the response `FAIL`. Vanilla doesn't know any more than that. It could be an issue with the hardware, the driver, or the operating system, but only someone with access to your system would be able to diagnose any further.

Ah so it's an adapter issue, currently we're playing jackbox so we'll get to this later probs... will update when it happens.

**Comment by lunakittyyy** [comment]
That's strange. If I'm understanding correctly, doesn't this mean a network scan is only failing if Vanilla does it?

GNOME settings shows that it can find networks fine:
![image](https://github.com/user-attachments/assets/ccbfc8d3-7f6e-4f84-a97e-a2012bf0840b)

Thank you for your time :)

**Comment by itsmattkc** [comment]
It's hard for me to say, `UNKNOWN SCAN RESPONSE: FAIL` is very rare and, by definition, means we don't know anything other than that `wpa_supplicant` returned `FAIL`.

It also may simply be a temporary/benign message. You haven't posted any other logs so I can't say that for sure either.

For more information, try using `wpa_supplicant_drc` directly:

In one terminal, browse to `<vanilla-dir>/bin` and enter:
```
sudo ./wpa_supplicant_drc -i <interface> -c /root/.vanilla/vanilla_wpa_key.conf
```

In a second terminal, enter:
```
sudo wpa_cli -p /var/run/wpa_supplicant_drc
scan
```

Keep entering `scan` periodically and see if it says `OK` or `FAIL` or provides any other information.

**Comment by lunakittyyy** [comment]
OK, thanks.

I've done that, and it seems to be doing things.
![image](https://github.com/user-attachments/assets/b73335a3-6e4c-4409-9f28-eff949a7e563)

It loops with:
```
<3>CTRL-EVENT-SCAN-STARTED 
<3>CTRL-EVENT-SCAN-RESULTS 
<3>WPS-AP-AVAILABLE
```
every couple of seconds ... it also said ``<3>CTRL-EVENT-NETWORK-NOT-FOUND`` once.

**Comment by lunakittyyy** [comment]
Um, nevermind? I don't know what I could have changed since this issue was created but now its working..
![image](https://github.com/user-attachments/assets/b7a2b25f-8898-4a96-93e9-4db076eab68f)

**Comment by itsmattkc** [comment]
Sounds like it might have been a temporary hardware issue. Glad you got it working.
