### ISSUE TITLE
INFO FAILED TO RUN DHCP ON wlp7s0

### ISSUE THREAD

**Issue by millionsofplayers** [vanilla-wiiu/vanilla#11]
synced successfully but i get this error and no output when i try to connect

**Comment by millionsofplayers** [comment]
does this need bluetooth to work?

**Comment by millionsofplayers** [comment]
I also can't build it on linux mint because it needs FFmpegConfig.cmake and/or ffmpeg-config.cmake

**Comment by millionsofplayers** [comment]
Trying on a computer with a Realtek RTL8821CE let's me connect but I don't get video. I didn't test the audio but I can control it until it finds out that it can't update it's firmware and kicks me out

**Comment by VoxelTek** [comment]
> INFO DHCLIENT DID NOT EXIT NORMALLY: 1 INFO FAILED TO RUN DHCP ON wlp7s0
> 
> Network controller: Intel Corporation Dual Band Wireless-AC 3168NGW [Stone Peak] (rev 10)

Any chance you could provide the entire log?



> I also can't build it on linux mint because it needs FFmpegConfig.cmake and/or ffmpeg-config.cmake

Yep, known issue. #9 fixes this.



> Trying on a computer with a Realtek RTL8821CE let's me connect but I don't get video. I didn't test the audio but I can control it until it finds out that it can't update it's firmware and kicks me out

Could you perhaps be a tad more specific? I'm a bit lost here.

@millionsofplayers

**Comment by millionsofplayers** [comment]
sorry for the late reply i forgot you'd replied

1. sure, here's the log file (wifi names removed)
[jun10again2.log](https://github.com/user-attachments/files/15780418/jun10again2.log)

3. i tried this on a family member's computer using a USB stick running EndeavorOS (nvidia). it lets me connect to the console completely fine, but when I hit connect, it doesn't show any video output. I wasn't sure if it had audio output since i didn't have any headphones on me i could test it with. I can control the console through the keyboard, but after I connected I got a pop-up saying that it wanted to check if the gamepad had an update. It didn't work and it sent me back to the login screen. After I logged into my account on the Wii U i could no longer control the console with the keyboard, as I'm guessing it unpaired the gamepad.

**Comment by VoxelTek** [comment]
```
INFO RECEIVED AUTHENTICATION FROM CONSOLE
INFO SAVING CONFIG
INFO SETTING wlp7s0 BACK TO MANAGED
INFO TEMPORARILY SET wlp7s0 TO UNMANAGED
INFO WAITING FOR CONNECTION
INFO CONNECTED TO CONSOLE
INFO Using system dhclient
INFO DHCLIENT DID NOT EXIT NORMALLY: 1
INFO FAILED TO RUN DHCP ON wlp7s0
INFO SETTING wlp7s0 BACK TO MANAGED
```

Ok, I think these are the main lines in question. I'll add the WiFi chipset to the wireless compatibility table.

Also, @millionsofplayers, did you use a USB adapter, or was this a PCIe card?

**Comment by millionsofplayers** [comment]
pcie card

**Comment by millionsofplayers** [comment]
How do I install the modified driver on arch? I followed the instructions but it failed

**Comment by VoxelTek** [comment]
I don't know if anyone has succeeded. I believe the modified driver was only suggested because someone modified the driver for use with DRC-Sim.

**Comment by itsmattkc** [comment]
@millionsofplayers It looks like you're self-compiling this. Do you have `dhclient` installed? What distro are you using? Have you tried using the prebuilt release?

**Comment by millionsofplayers** [comment]
> @millionsofplayers It looks like you're self-compiling this. Do you have `dhclient` installed? What distro are you using? Have you tried using the prebuilt release?

I did build it with the computer with the AC 3168NGW, which also had dhclient (it runs arch), and on another pc which runs linux mint I tried the prebuild release (the one with the RTL8821CE)

**Comment by itsmattkc** [comment]
Yeah I'm referring to the Intel AC 3168 setup in the OP, did you try the prebuilt release on that?

The `DHCLIENT DID NOT EXIT NORMALLY` is most likely the problem here. I'm not sure why it's throwing an error on your setup, but the prebuilt release comes with its own version of `dhclient` that would be worth a try.

Alternatively, try running `sudo dhclient -v wlp7s0` after that message appears (keep Vanilla running/connected) to see what error it's throwing.

**Comment by millionsofplayers** [comment]
Prebuild works, thank you

**Comment by itsmattkc** [comment]
@millionsofplayers For your Linux Mint setup with `RTL8821CE`, do you know if there's a firewall set up that might be blocking incoming connections?

For reference, the Wii U and gamepad communicate through UDP ports, and based on your description, it sounds like outbound packets (controller input) are working, but inbound packets (video/audio) are not. This would make sense if a firewall was blocking incoming connections unless otherwise excepted, which is a fairly common default configuration.
