### ISSUE TITLE
Support Raspberry Pi hardware decoding

### ISSUE THREAD

**Issue by itsmattkc** [vanilla-wiiu/vanilla#28]
Currently the video lags on my testing system (Pi 3 Model B) and it is likely because we currently use software decoding (through FFmpeg). Supposedly the Pi 3 [is capable of decoding 1080p30](https://datasheets.raspberrypi.com/rpi3/raspberry-pi-3-a-plus-product-brief.pdf), which should be more than enough for the gamepad's 480p60 feed.

**Comment by jdfr228** [comment]
Just curious, given reports of the Steam Deck video lagging as well (which seems surprising, I would think it could brute force software decoding), if hardware decoding is feasible or can be implemented generally enough to be relatively cross-platform.

**Comment by itsmattkc** [comment]
> Just curious, given reports of the Steam Deck video lagging as well (which seems surprising, I would think it could brute force software decoding), if hardware decoding is feasible or can be implemented generally enough to be relatively cross-platform.

While zero copy hardware decoding to screen is desirable wherever it's available, I wouldn't assume the apparent Steam Deck lag is caused by the software decoding.

**Comment by SpaceBurn** [comment]
Correct me if i'm wrong, but doesn't FFMEPG already support hardware decoding?

**Comment by itsmattkc** [comment]
It does, but it's not quite that simple. To get the most out of hardware decoding, you need to be able to send the decoded frame straight to the screen without making a slow roundtrip back to the CPU. This requires some fairly complex interaction between whatever decoding API being used (e.g. VAAPI, NVDEC, V4L2M2M) and OpenGL that FFmpeg cannot facilitate.

**Comment by itsmattkc** [comment]
Implemented in 7587f805fd0e239e2209e7775996821b5fb3d4f0
