### ISSUE TITLE
`dhclient` doesn't stop upon disconnect

### ISSUE THREAD

**Issue by RoblKyogre** [vanilla-wiiu/vanilla#31]
Using the latest continuous build as of this issue (https://github.com/vanilla-wiiu/vanilla/commit/175610f622a47fef2c43bea920ae60ccc7fa9aed), `dhclient` doesn't get stopped when disconnecting, causing future attempts to connect to fail since `dhclient` exits if it detects another instance is already running. Even after exiting the program, `htop` shows that the `dhclient` included with the release is still running, meaning I have to run `sudo killall dhclient` to get it to stop. For reference, I'm running Arch Linux with the `6.9.3-zen1-1-zen` kernel on KDE Plasma 6.0.5, and my wifi adapter is detected as `wlp0s20f3`.

Here's the output I got when running this from the terminal (I connected to the console, disconnected, then attempted to connect again):
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
No QtMultimedia backends found. Only QMediaDevices, QAudioDevice, QSoundEffect, QAudioSink, and QAudioSource are available.
Established connection with backend
INFO TEMPORARILY SET wlp0s20f3 TO UNMANAGED
wpa_supplicant_drc: no process found
INFO WAITING FOR CONNECTION
INFO CONNECTED TO CONSOLE
INFO Using custom dhclient at: /home/roblkyogre/Documents/Apps/Vanilla_U-x86_64/usr/bin/dhclient
INFO DHCP ESTABLISHED
INFO SETTING wlp0s20f3 BACK TO MANAGED
INFO TEMPORARILY SET wlp0s20f3 TO UNMANAGED
INFO WAITING FOR CONNECTION
INFO WAITING FOR CONNECTION
INFO CONNECTED TO CONSOLE
INFO Using custom dhclient at: /home/roblkyogre/Documents/Apps/Vanilla_U-x86_64/usr/bin/dhclient
dhclient(557822) is already running - exiting.

This version of ISC DHCP is based on the release available
on ftp.isc.org. Features have been added and other changes
have been made to the base software release in order to make
it work better with this distribution.

Please report issues with this software via:
https://gitlab.archlinux.org/groups/archlinux/-/issues

exiting.
INFO DHCLIENT DID NOT EXIT NORMALLY: 1
INFO FAILED TO RUN DHCP ON wlp0s20f3
INFO SETTING wlp0s20f3 BACK TO MANAGED
```

**Comment by itsmattkc** [comment]
Yes this appears to be caused by my recent switch from Ubuntu-based Docker images to Alma Linux (which presumably installs a different version of dhclient). There's probably a parameter I can pass to restore the old behavior but I haven't determined what it is yet.
