### ISSUE TITLE
Hardware Compatibility

### ISSUE THREAD

**Issue by itsmattkc** [vanilla-wiiu/vanilla#33]
I/we would love to hear how Vanilla works on your setup! There is currently a [wiki page](/vanilla-wiiu/vanilla/wiki/Wireless-Compatibility) which is publicly editable that you can add your results too. Additionally, if you have further information/questions that don't fit into the page, feel free to make a [Discussions](/vanilla-wiiu/vanilla/discussions) thread and link it to your entry on the wiki page.

Thanks for testing Vanilla!

**Comment by LhymeFruit** [comment]
how do I go about making a compatability report about a laptop's network card? I dont know how to get information about it and i also dont know how to contribute to the compatability sheet
