### ISSUE TITLE
Vainilla in WSL

### ISSUE THREAD

**Issue by XxAlcatelxX** [vanilla-wiiu/vanilla#39]
I heard that someone was able to run this program on Windows with the help of the Ubuntu (WSL) program in the Microsoft Store, could anyone help me with that?

**Comment by WiiUEnthusiast** [comment]
If WSL really is just Linux terminal inside windows then its fairly simple to just follow the same instructions Matt gave in the compiling process
running the program however is hard considering how Windows Qt is different in compiling than Linux Qt and i don't think there is a Windows binary yet so i guess the answer is either a virtual machine or dual-booting just for the sake of convenience
If your not satisfied with this answer you could follow this guide
https://askubuntu.com/questions/1428981/wsl2-on-windows-11-ubuntu-20-04-cannot-run-qt-apps-could-not-connect-to-dis

**Comment by itsmattkc** [comment]
I would be pessimistic about the prospects of running Vanilla in WSL. Vanilla (or more specifically our modified `wpa_supplicant`) requires fairly direct access to the OS Wi-Fi stack - I doubt WSL exposes enough to be useful.

In the future, it should be possible to run the backend (`vanilla-pipe`) in a Linux virtual machine (with Wi-Fi hardware passed through) while using the frontend on Windows. It's cumbersome but it would work. It may also be possible to run the modified `wpa_supplicant` on Windows for a fully native setup, but I suspect that's a long shot.

**Comment by XxAlcatelxX** [comment]
> I would be pessimistic about the prospects of running Vanilla in WSL. Vanilla (or more specifically our modified `wpa_supplicant`) requires fairly direct access to the OS Wi-Fi stack - I doubt WSL exposes enough to be useful.
> 
> In the future, it should be possible to run the backend (`vanilla-pipe`) in a Linux virtual machine (with Wi-Fi hardware passed through) while using the frontend on Windows. It's cumbersome but it would work. It may also be possible to run the modified `wpa_supplicant` on Windows for a fully native setup, but I suspect that's a long shot.

I am looking for a way to run the program in WSL because using the Virtual Machine will require me to use a USB Wifi Interface, something that I currently cannot acquire

**Comment by XxAlcatelxX** [comment]
> I would be pessimistic about the prospects of running Vanilla in WSL. Vanilla (or more specifically our modified `wpa_supplicant`) requires fairly direct access to the OS Wi-Fi stack - I doubt WSL exposes enough to be useful.
> 
> In the future, it should be possible to run the backend (`vanilla-pipe`) in a Linux virtual machine (with Wi-Fi hardware passed through) while using the frontend on Windows. It's cumbersome but it would work. It may also be possible to run the modified `wpa_supplicant` on Windows for a fully native setup, but I suspect that's a long shot.

Likewise, I am currently installing Kali Linux (a Debian-based distribution) on a Flash Drive so I can avoid making volumes on my SSD, since I take up free space

**Comment by itsmattkc** [comment]
> I am looking for a way to run the program in WSL because using the Virtual Machine will require me to use a USB Wifi Interface, something that I currently cannot acquire

Many virtual machines allow for PCI passthrough, but if you can't pass anything through to a VM, it's unlikely you'll be able to pass anything through to WSL.

Likely related: microsoft/WSL#11444

**Comment by WiiUEnthusiast** [comment]
I Tried Editing The Code In Qt For Windows And Recompiled It Just For It To Yell At Me And Tell Me That The Code Supposedly Was Made On An ARM Machine

**Comment by spicyegg234** [comment]
ahahaa... ummm.
https://github.com/vanilla-wiiu/vanilla/discussions/496
yes. it is possible!
