### ISSUE TITLE
Intel 8265 compatibility

### ISSUE THREAD

**Issue by UwUnyaa** [vanilla-wiiu/vanilla#41]
Just checked that the software works on my Intel 8265 card. No surprises, it works as expected. Using a thinkpad T480, running arch.

Here's the relevant line from `lspci`:
```
03:00.0 Network controller: Intel Corporation Wireless 8265 / 8275 (rev 78)
```

**Comment by VoxelTek** [comment]
Cool, I'll make sure this is properly added to the compatibility table. In the meantime, do you think it might be possible for you to move this issue to a Discussion?

**Comment by UwUnyaa** [comment]
https://github.com/vanilla-wiiu/vanilla/discussions/42

I've created a discussion thread as suggested, and am closing this to avoid duplication.
