### ISSUE TITLE
Can't seem to get Vanilla running on Laptop/PC.

### ISSUE THREAD

**Issue by AndrewDTR** [vanilla-wiiu/vanilla#47]
Hi folks. Wondering if I just have a bad case of both my laptop & PC being incompatible or whether it's user error/a networking issue. 

On my laptop I can sync fine, but get stuck in an endless loop when attempting to connect:

```
draw@draw-Surface-Laptop-2:~/Downloads/hey$ ./AppRun 
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
No QtMultimedia backends found. Only QMediaDevices, QAudioDevice, QSoundEffect, QAudioSink, and QAudioSource are available.
Established connection with backend
INFO TEMPORARILY SET wlp2s0 TO UNMANAGED
wpa_supplicant_drc: no process found
INFO RECEIVED SCAN RESULTS
INFO RECEIVED SCAN RESULTS
INFO FOUND WII U, TESTING WPS PIN
INFO CRED RECV: <3>CTRL-EVENT-BSS-ADDED 57 [redacted]sid
INFO CRED RECV: <3>CTRL-EVENT-BSS-ADDED 58 [redacted]sid
INFO CRED RECV: <3>CTRL-EVENT-BSS-ADDED 59 [redacted]sid
INFO CRED RECV: <3>CTRL-EVENT-BSS-ADDED 60 [redacted]sid
INFO CRED RECV: <3>CTRL-EVENT-BSS-ADDED 61 [redacted]sid
INFO CRED RECV: <3>CTRL-EVENT-BSS-ADDED 62 [redacted]sid
INFO CRED RECV: <3>CTRL-EVENT-BSS-ADDED 63 [redacted]sid
INFO CRED RECV: <3>CTRL-EVENT-SCAN-RESULTS [redacted]sid
INFO CRED RECV: <3>WPS-AP-AVAILABLE ESULTS [redacted]sid
INFO CRED RECV: <3>Trying to associate with [redacted] (SSID='WiiU[redacted]_STA1' freq=5825 MHz)[redacted]	5220	-24	[WPA2-?][ESS]	
INFO CRED RECV: <3>Associated with [redacted] (SSID='WiiU[redacted]_STA1' freq=5825 MHz)[redacted]	5220	-24	[WPA2-?][ESS]	
INFO CRED RECV: <3>CTRL-EVENT-SUBNET-STATUS-UPDATE status=0 (SSID='WiiU[redacted]_STA1' freq=5825 MHz)[redacted]	5220	-24	[WPA2-?][ESS]	
INFO CRED RECV: <3>CTRL-EVENT-EAP-STARTED EAP authentication started 'WiiU[redacted]_STA1' freq=5825 MHz)[redacted]	5220	-24	[WPA2-?][ESS]	
INFO CRED RECV: <3>CTRL-EVENT-EAP-STATUS status='started' parameter='' WiiU[redacted]_STA1' freq=5825 MHz)[redacted]	5220	-24	[WPA2-?][ESS]	
INFO CRED RECV: <3>CTRL-EVENT-EAP-PROPOSED-METHOD vendor=14122 method=1 WiiU[redacted]_STA1' freq=5825 MHz)[redacted]	5220	-24	[WPA2-?][ESS]	
INFO CRED RECV: <3>CTRL-EVENT-EAP-STATUS status='accept proposed method' parameter='WSC' WiiU[redacted]_STA1' freq=5825 MHz)[redacted]	5220	-24	[WPA2-?][ESS]	
INFO CRED RECV: <3>CTRL-EVENT-EAP-METHOD EAP vendor 14122 method 1 (WSC) selected WiiU[redacted]_STA1' freq=5825 MHz)[redacted]	5220	-24	[WPA2-?][ESS]	
INFO CRED RECV: <3>WPS-CRED-RECEIVED HOD EAP vendor 14122 method 1 (WSC) selected WiiU[redacted]_STA1' freq=5825 MHz)[redacted]	5220	-24	[WPA2-?][ESS]	
INFO RECEIVED AUTHENTICATION FROM CONSOLE
INFO SAVING CONFIG
INFO SETTING wlp2s0 BACK TO MANAGED
INFO TEMPORARILY SET wlp2s0 TO UNMANAGED
INFO WAITING FOR CONNECTION
INFO WAITING FOR CONNECTION

// (continued, until...) //

INFO WAITING FOR CONNECTION
INFO WAITING FOR CONNECTIONINFO WAITING FOR CONNECTION
INFO SETTING wlp2s0 BACK TO MANAGED
```
...until I forcefully quit it. On my desktop, I get stuck at an infinite loop of `INFO RECEIVED SCAN RESULTS` when attempting to scan for the Wii U. Any help to get connected would be greatly appreciated. Thanks.

**Comment by VoxelTek** [comment]
Hey! May I ask, what's your WiFi card?

**Comment by Herop113** [comment]
> Hey! May I ask, what's your WiFi card?

can i ask? i can't seem to get this to work. I use ubuntu on vmware. i got to install everything. my wifi card is Realtek 8821CU 802.11ac usb NIC. I only got it to sync once. it show successful pairing but didn't show anything. now it won't sync at all .

**Comment by AndrewDTR** [comment]
> Hey! May I ask, what's your WiFi card?

Hi! On my laptop (syncs fine, just doesn't connect) I have a Marvell 88W8897. On my desktop (which can't sync with the console at all) I have a Mediatek RZ608.

**Comment by VoxelTek** [comment]
@Herop113 I believe you may need to use a native machine instead of simply a virtual machine, as this requires quite low-level hardware access that I'm not sure a virtual machine can provide. Additionally, your specific card has never been tested, and you may need to use an alternate WiFi driver to get this to work. If the issue still occurs when running Linux natively, feel free to seek support and create your own issue.


@AndrewDTR Hm, I don't believe either of your WiFi cards have been tested before. It seems like both cards may not be compatible at the moment, however the only way to know for sure would be to test with a known-good card. At this point, though, it does seem that an incompatible WiFi card is your most likely problem.

**Comment by Herop113** [comment]
@VoxelTek I don't have a spare one only main pc running window. and i already installed that alternate wifi driver. before that driver i got nothing but after installed it successfully sync but afterward nothing happen when i tried to connect

**Comment by VoxelTek** [comment]
@Herop113 again, not the same issue as this. Using a virtual machine is not a supported way of using Vanilla, and is unrelated to the issues currently being experienced here.

**Comment by AndrewDTR** [comment]
> @AndrewDTR Hm, I don't believe either of your WiFi cards have been tested before. It seems like both cards may not be compatible at the moment, however the only way to know for sure would be to test with a known-good card. At this point, though, it does seem that an incompatible WiFi card is your most likely problem.

Ah, gotcha -- that sucks, but what can ya do. Thank you anyways!

**Comment by Herop113** [comment]
@VoxelTek ok, thanks for your reply.
