### ISSUE TITLE
any way to use this on steam os without a root account password

### ISSUE THREAD

**Issue by jbmanlol** [vanilla-wiiu/vanilla#50]
I forgot my root password for steam os and I do not know what to do and also I feel like i really want a windows build or try to run it via windows subsystem for linux or something

**Comment by itsmattkc** [comment]
Unfortunately no, Vanilla requires relatively low level access to Wi-Fi hardware, which root permissions in one way or another.

**Comment by jbmanlol** [comment]
oh ok so then how do I reset it via cmd
