### ISSUE TITLE
Windows port?

### ISSUE THREAD

**Issue by FredericVincent0** [vanilla-wiiu/vanilla#53]
would it be possible in the future to port the project to windows?

**Comment by itsmattkc** [comment]
It may be possible, but it's unlikely. Vanilla requires fairly low level access to the networking stack that I'm not confident would be provided by either Windows or macOS. It may be doable, and if someone with more knowledge of those OS' networking stacks wants to give it a try, it'd be interesting to see, but I have a feeling only Linux/BSD provide enough control to pull it off.

I don't think desktop PCs should be the main priority anyway, ultimately the goal is to get this running on portable devices like phones. But Linux is useful as both a development platform and for certain embedded portable devices (Steam Deck, Raspberry Pi, modded Nintendo Switch, etc.) so it made sense to release for it first.
