### ISSUE TITLE
Motion Controls inverted

### ISSUE THREAD

**Issue by FredericVincent0** [vanilla-wiiu/vanilla#60]
The motion controls with controller are inverted i don't know if all controller are affected to this issue? im using a switch pro controller btw

**Comment by itsmattkc** [comment]
Can you provide an example case that can be reliably tested? My tests were all accurate to the original controller (albeit with a DualShock 4)

**Comment by FredericVincent0** [comment]
Sorry i think is my controller driver the problem can you close this issue
please sorry
