### ISSUE TITLE
Switch pro controller not recognized

### ISSUE THREAD

**Issue by FredericVincent0** [vanilla-wiiu/vanilla#64]
Switch pro controller not recognized by Vanilla i try joycond but the motion control are inverted with joycond but the controller still recognized by vanilla i install the kernel with the nintendo hid module but no luck with vanilla😮‍💨

**Comment by itsmattkc** [comment]
Vanilla uses SDL2 to interface with controllers, is there any way you can test whether your controller works with SDL2 on your end? (emulators like PCSX2 and Retroarch can be configured to use SDL2 for input).

**Comment by FredericVincent0** [comment]
Ok i will try Do i need to install sdl2 or not?

**Comment by FredericVincent0** [comment]
ok i try with dolphin and my controller have sdl2
![Capture d’écran du 2024-08-13 08-54-48](https://github.com/user-attachments/assets/1c43d670-5ace-4921-9939-3e383f8b6d4e)

**Comment by FredericVincent0** [comment]
but in vanilla the controller still not recognized

**Comment by FredericVincent0** [comment]
ok now i build vanilla and the controller show up but do noting
![Capture d’écran du 2024-08-13 09-55-39](https://github.com/user-attachments/assets/f7e9f6e9-308d-416d-a1ec-2910c4173fee)

**Comment by FredericVincent0** [comment]
has vanilla wii u already implemented the gyroscope? because if it hasn't, this problem can be closed I think because you'd need a pull request to implement it unless that pull request already exists?

**Comment by itsmattkc** [comment]
Vanilla has gyroscope support.

**Comment by FredericVincent0** [comment]
Why don't I have the gyroscope on the Switch Pro Controller? I don't get it.

**Comment by itsmattkc** [comment]
I don't know why it isn't working for you. Vanilla uses SDL2 for its gyroscope capability too, if it doesn't work, it's because SDL2 isn't picking it up for some reason.

**Comment by FredericVincent0** [comment]
how do I fix it?

**Comment by FredericVincent0** [comment]
i install sdl but not work

**Comment by itsmattkc** [comment]
I couldn't say since I don't have access to your setup. I don't know what distro/input API/kernel/hardware/etc. you're using, and even if I did, I still may not be able to reproduce your setup myself to accurately determine what's preventing the gyroscope from working. Im afraid you'll probably have to research/troubleshoot this yourself.

**Comment by FredericVincent0** [comment]
How do I get you to access my system configuration?

**Comment by WinFan3672** [comment]
> How do I get you to access my system configuration?

You can't. Even if you sent Matt your laptop or something, I doubt he has the time to fix it himself - he's a busy guy from what I can tell. You'll just have to work it out on your own.

**Comment by FredericVincent0** [comment]
Ok

Le lun. 16 sept. 2024, 11 h 00, Gordinator ***@***.***> a
écrit :

**Comment by wizardkitty** [comment]
I will say on my system as well I have not gotten gyro support to work with my switch pro controller. I might try different a different distribution but right now it has not worked for me.

**Comment by FredericVincent0** [comment]
Ok, let me know.

Le mer. 18 sept. 2024, 16 h 06, wizardkitty ***@***.***> a
écrit :

**Comment by FredericVincent0** [comment]
@wizardkitty I finally managed to get the gyroscope working on ubuntu, indeed the build in the release section does not work with the gyroscope, you have to install the prerequisites then build vanilla and I launched the vanilla-gui executable with the terminal ./vanilla-gui to see the log and no errors are displayed the other build had qt errors

**Comment by FredericVincent0** [comment]
@wizardkitty so as this is not an error with ubuntu or any other distribution i think i don't know if this issue should be closed tell me

**Comment by wizardkitty** [comment]
> @wizardkitty I finally managed to get the gyroscope working on ubuntu, indeed the build in the release section does not work with the gyroscope, you have to install the prerequisites then build vanilla and I launched the vanilla-gui executable with the terminal ./vanilla-gui to see the log and no errors are displayed the other build had qt errors

Probably means that there could be a issue with the github compliation or that vanilla needs a warning for missing dependicies.

**Comment by FredericVincent0** [comment]
Ho ok

Le sam. 28 sept. 2024, 16 h 55, wizardkitty ***@***.***> a
écrit :

**Comment by itsmattkc** [comment]
Glad to see this was solved. It's most likely that the SDL2 from your distro is better suited to the distro than the one in the build (which is based on Alma Linux), so I would recommend others having trouble with controllers to try self-compiling Vanilla too.
