### ISSUE TITLE
Vanilla no longer working in Debian Trixie

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [vanilla-wiiu/vanilla#66]
I'm not sure when, but at some point, some package update in Debian seems to have broken Vanilla in Debian Trixie (aka Debian Testing or Debian 13). I used Trixie to test two Intel cards back in June, and it worked then, but now I've tried to use it again on both systems, and on both of them, it pairs, but when I try to connect, I get no video, audio, or button input. 

Terminal log (Wi-Fi card in this log was an Intel AC 9560): https://pastebin.com/xitnZDHa

**Comment by itsmattkc** [comment]
Hmm, the relevant error is:

```
INFO SUBPROCESS /home/ella/Downloads/Vanilla_U-x86_64(2)/usr/bin/../sbin/dhclient-script: line 248: /sbin/ip: No such file or directory
```

Supposedly on your distro, the `ip` command is not located in `/sbin` as is expected by Vanilla's `dhclient-script` (taken straight from the dhclient repository). Perhaps the smarter thing to do would be to attempt using the system's `dhclient-script` if it already exists, since the paths will probably be corrected for your distro there.

Does your system have a `/sbin/dhclient-script`?

**Comment by Lost-Entrepreneur439** [comment]
> Hmm, the relevant error is:
> 
> ```
> INFO SUBPROCESS /home/ella/Downloads/Vanilla_U-x86_64(2)/usr/bin/../sbin/dhclient-script: line 248: /sbin/ip: No such file or directory
> ```
> 
> Supposedly on your distro, the `ip` command is not located in `/sbin` as is expected by Vanilla's `dhclient-script` (taken [straight from the dhclient repository](https://github.com/isc-projects/dhcp/blob/master/client/scripts/linux)). Perhaps the smarter thing to do would be to attempt using the system's `dhclient-script` if it already exists, since the paths will probably be corrected for your distro there.
> 
> Does your system have a `/sbin/dhclient-script`?

Both systems I tested on did have /sbin/dhclient-script. So I tried it on both systems.

For future reference - The laptops are a Dell Latitude E6430 (i5-3380m, Intel HD Graphics 4000, Intel Centrino Advanced-N 6205) and a Lenovo 500e Chromebook 2nd generation (Celeron N4120, UHD Graphics 600, Intel AC 9560). To make things simpler, I'll refer to the Dell as "laptop 1" and the Lenovo as "laptop 2".

On laptop 2, no issues after replacing Vanilla's dhclient-script with the one from my system's sbin, it paired and worked perfectly afterwards. However, on laptop 1, after replacing the dhclient-script, I was able to connect and send button inputs to the Wii U, but video was completely black. Here's a log from laptop 1:

**Comment by itsmattkc** [comment]
Can you send the wireless adapter model for laptop 1? Should show up in `lspci`

**Comment by Lost-Entrepreneur439** [comment]
> Can you send the wireless adapter model for laptop 1? Should show up in `lspci`

`02:00.0 Network controller: Intel Corporation Centrino Advanced-N 6205 [Taylor Peak] (rev 34)`

**Comment by itsmattkc** [comment]
I'm not sure why it wasn't working on that adapter. Since the main issue was addressed and the code has changed significantly since this issue, there's probably not much point in keeping it open. If there are further issues, feel free to open another.
