### ISSUE TITLE
error on AArch64 Version

### ISSUE THREAD

**Issue by whistler2000** [vanilla-wiiu/vanilla#70]
hi so the error i get is error while loading shared libraries: libvanilla.so: ELF load command address/offset not page-aligned

**Comment by whistler2000** [comment]
Error does not happen when i compiled it, the error only happens in the pre compiled ver, aarch64 precompiled build possibly has x86 lib files

**Comment by itsmattkc** [comment]
This is a known issue. Seems to be caused by patchelf, which is used to create the deployment package. Follow the issue on their end: NixOS/patchelf#492
