### ISSUE TITLE
Support for using keyboard and controllers as input simultaneously?

### ISSUE THREAD

**Issue by mjdxp** [vanilla-wiiu/vanilla#79]
Hello, I've installed this on my Steam Deck and it's amazing. Pretty much everything works, except there's no Home button on the Steam Deck, and no way to map a button to Home in the Steam OS button remapping settings. The only way to have a Home button is to either use keyboard controls and set up Steam OS' button mappings to use the keyboard buttons for the controls, or to exit fullscreen, switch inputs, press a button mapped to Home, switch back to gamepad controls again, then enter fullscreen again. The first option means you don't get analog sticks, the second is extremely tedious. The best way I can think to fix this would be to have a mode where both keyboard and controller inputs are accepted by the app at once. Could this potentially be added, or at least some other solution I'm not thinking of?

**Comment by itsmattkc** [comment]
Merging into #107
