### ISSUE TITLE
How do i get this running on android?

### ISSUE THREAD

**Issue by SuperMarioYAHOOYAHOO** [vanilla-wiiu/vanilla#81]
I would like to test some of my android devices with vanilla. I am unsure where to start, do i need to build from source, or is there an apk and im just stupid.

**Comment by un-simp** [comment]
That it currently not apart of the scope for this specific project however it is being considered and (shameless self plug) i am currently working on bindings for android also i think matt had a prototype of the ui at somepoint

**Comment by SuperMarioYAHOOYAHOO** [comment]
> That it currently not apart of the scope for this specific project however it is being worked on and (shameless self plug) i am currently working on bindings for android also i think matt had a prototype of the ui at somepoint

sorry. just saw that the readme said it was for android and assumed. Thank you.

**Comment by pchclx** [comment]
> That it currently not apart of the scope for this specific project however it is being worked on and (shameless self plug) i am currently working on bindings for android also i think matt had a prototype of the ui at somepoint

any further update on this un-simp? would be amazing to get working on a tablet
