### ISSUE TITLE
Getting the Steam Deck to connect to the Wii U.

### ISSUE THREAD

**Issue by notliam1** [vanilla-wiiu/vanilla#82]
Hey, I tried connecting to the Wii U after syncing successfully and I've encountered that I don't get any video, I did manage to get video one time but only a singular frame of the Wii U settings. My Wii U doesn't have access to the internet and my Gamepad is out of charge (I ordered a new cable). The Wii U does show that a gamepad is connected I just don't get any video from the display.

**Comment by SwampertTube** [comment]
I have an issue with this too, I tried connecting mine to my Steam Deck OLED and it just doesn't connect at all.

**Comment by notliam1** [comment]
> I have an issue with this too, I tried connecting mine to my Steam Deck OLED and it just doesn't connect at all.

Hey!, I managed to "fix" it by changing the network config. It is the only way I found to actually fix it while the dev's are unaware
###
sudo mv /etc/NetworkManager/conf.d/wifi_backend.conf /etc/NetworkManager/conf.d/wifi_backend.conf.bak
sudo reboot
### 
changed the network backend to wpa_supplicant.

**Comment by itsmattkc** [comment]
Merging into #107
