### ISSUE TITLE
FAILED TO BIND PORT 51000: 98

### ISSUE THREAD

**Issue by Lillyliv7** [vanilla-wiiu/vanilla#88]
When trying to sync with wii u, the error "FAILED TO BIND PORT 51000: 98" appears in the console and it gets stuck on "Connecting to the Wii U console...", when cancelling the error "INFO FAILED TO BIND TO PIPE" appears. My wifi device is a BCM4331 inside a 2012 imac running ubuntu.

**Comment by itsmattkc** [comment]
Error 98 implies something else on your system is using port 51000. This is the port currently used by `vanilla-gui` to communicate with `vanilla-pipe`. Is there something on your system already using that port?

Also just to warn you, BCM devices almost never work with the Wii U due to the way they're designed. You'll likely need a external USB Wi-Fi adapter to connect successfully.

**Comment by Lillyliv7** [comment]
> Error 98 implies something else on your system is using port 51000. This is the port currently used by `vanilla-gui` to communicate with `vanilla-pipe`. Is there something on your system already using that port?
> 
> Also just to warn you, BCM devices almost never work with the Wii U due to the way they're designed. You'll likely need a external USB Wi-Fi adapter to connect successfully.

i got it to work without that error fine with an external wifi adapter, not really sure what else was using the port but it seems to have stopped, ty for responding also!

**Comment by tbejos** [comment]
I ran into this issue when Wi-Fi was "off" in gnome setting on Arch Linux. It is possible that if it wasn't being used the wifi adapter was in a state where it couldn't be used

**Comment by itsmattkc** [comment]
Going to close this issue as solved.

For future reference, it's possible for `vanilla-gui` to crash in a way that `vanilla-pipe` (which binds to port 51000) doesn't terminate with it, leaving its ports occupied and unusable by any other Vanilla instances. Running this command should solve that:

```
sudo killall -9 vanilla-pipe
```

Or you can restart your computer, which will naturally terminate any extant `vanilla-pipe` processes. Other than that, you'll have to investigate what else might be using port 51000 on your system.
