### ISSUE TITLE
stuck on connecting

### ISSUE THREAD

**Issue by Cart1416** [vanilla-wiiu/vanilla#95]
I am using a tp link archer t3u plus with the correct linux driver installed on debian 12 but my wii u won't connect to the pc anymore, it worked fine a month ago but has suddenly not worked, the only thing I've changed is motherboard and cpu with a gigabyte and i7-12700, previously i3-7100
I've attached the log from konsole
[log.txt](https://github.com/user-attachments/files/17605309/log.txt)

**Comment by itsmattkc** [comment]
The console is rejecting the WPS authentication. It's hard to say why from the log - are you sure you got the sync code right? Are you sure your system is still using the `rtw88` driver?

**Comment by Cart1416** [comment]
edit: I also tried it on my old motherboard+cpu with the same wifi dongle and debian 12 but it gives the same error

**Comment by Cart1416** [comment]
I always used the rtl88x2bu driver from this guide
[https://community.tp-link.com/en/home/forum/topic/277278)](https://community.tp-link.com/en/home/forum/topic/277278)

**Comment by itsmattkc** [comment]
I would recommend trying this driver instead: https://github.com/lwfinger/rtw88

**Comment by Cart1416** [comment]
this driver works! I uninstalled the old driver with dkms and installed the new one (secure boot off) there was a small problem when pairing where the screen was black but I pressed ok with a wii remote and it works great

**Comment by Cart1416** [comment]
so after I connected vanilla is acting very strange, I can't input and the screen is black until I switch titles or press home

**Comment by itsmattkc** [comment]
Sounds like a duplicate of #80, discussion should continue there.
