### ISSUE TITLE
Route smarter after acquiring DHCP lease

### ISSUE THREAD

**Issue by itsmattkc** [vanilla-wiiu/vanilla#96]
Currently we let `dhclient` route the OS to try networking via the Wii U and then immediately try to undo that route in `vanilla-pipe`. Sometimes this appears to fail (and is kind of a hacky solution to begin with).

We should try and figure out a way to make our DHCP client not create this route to begin with. I think the technical way with `dhclient` would be to modify the `dhclient-script`, however `dhclient` is also EOL (#77) so the solution we use should probably be tailored for a different DHCP client. There's an argument to have our own built-in DHCP client since DHCP is frequently built into programs (e.g. NetworkManager).

**Comment by blackwizard-BE** [comment]
same
